### ISSUE TITLE
dial tcp :0: connect: connection refused

### ISSUE THREAD

**Issue by michael-keyes** [uberswe/golang-base-project#22]
I'm unable to connect to a postgres database when **not** using docker.
I used the docker image to get the postgres schema, but was unable to connect when trying to run via Go directly. Would be possible to include an example .sql file?

**Comment by uberswe** [comment]
It should work fine with or without docker so this seems like there may be something wrong with your local environment or that you are missing some env variables. Are you setting all of them to the correct values?

There is some example code for connecting to PostgreSQL in the gorm documentation, maybe you could see if it works using the example code provided there? https://gorm.io/docs/connecting_to_the_database.html#PostgreSQL

**Comment by michael-keyes** [comment]
Env variables are being set correctly, but perhaps postgres schema/user I'm using is flawed in some way. Thanks for getting back to me. I'll check the gorm docs. Thanks a lot.

**Comment by michael-keyes** [comment]
Here is the dump.sql I'm using to import to local instance of postgres, Any glaring  issues?
 
--
-- PostgreSQL database dump
--

-- Dumped from database version 14.5 (Debian 14.5-2.pgdg110+2)
-- Dumped by pg_dump version 14.5 (Debian 14.5-2.pgdg110+2)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: sessions; Type: TABLE; Schema: public; Owner: base_project
--

CREATE TABLE public.sessions (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    identifier text,
    user_id bigint,
    expires_at timestamp with time zone
);


ALTER TABLE public.sessions OWNER TO base_project;

--
-- Name: sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: base_project
--

CREATE SEQUENCE public.sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.sessions_id_seq OWNER TO base_project;

--
-- Name: sessions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: base_project
--

ALTER SEQUENCE public.sessions_id_seq OWNED BY public.sessions.id;


--
-- Name: tokens; Type: TABLE; Schema: public; Owner: base_project
--

CREATE TABLE public.tokens (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    value text,
    type text,
    model_id bigint,
    model_type text,
    expires_at timestamp with time zone
);


ALTER TABLE public.tokens OWNER TO base_project;

--
-- Name: tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: base_project
--

CREATE SEQUENCE public.tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.tokens_id_seq OWNER TO base_project;

--
-- Name: tokens_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: base_project
--

ALTER SEQUENCE public.tokens_id_seq OWNED BY public.tokens.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: base_project
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    email text,
    password text,
    activated_at timestamp with time zone
);


ALTER TABLE public.users OWNER TO base_project;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: base_project
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.users_id_seq OWNER TO base_project;

--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: base_project
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: websites; Type: TABLE; Schema: public; Owner: base_project
--

CREATE TABLE public.websites (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    updated_at timestamp with time zone,
    deleted_at timestamp with time zone,
    title text,
    description text,
    url text
);


ALTER TABLE public.websites OWNER TO base_project;

--
-- Name: websites_id_seq; Type: SEQUENCE; Schema: public; Owner: base_project
--

CREATE SEQUENCE public.websites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.websites_id_seq OWNER TO base_project;

--
-- Name: websites_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: base_project
--

ALTER SEQUENCE public.websites_id_seq OWNED BY public.websites.id;


--
-- Name: sessions id; Type: DEFAULT; Schema: public; Owner: base_project
--

ALTER TABLE ONLY public.sessions ALTER COLUMN id SET DEFAULT nextval('public.sessions_id_seq'::regclass);


--
-- Name: tokens id; Type: DEFAULT; Schema: public; Owner: base_project
--

ALTER TABLE ONLY public.tokens ALTER COLUMN id SET DEFAULT nextval('public.tokens_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: base_project
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: websites id; Type: DEFAULT; Schema: public; Owner: base_project
--

ALTER TABLE ONLY public.websites ALTER COLUMN id SET DEFAULT nextval('public.websites_id_seq'::regclass);


--
-- Data for Name: sessions; Type: TABLE DATA; Schema: public; Owner: base_project
--

COPY public.sessions (id, created_at, updated_at, deleted_at, identifier, user_id, expires_at) FROM stdin;
\.


--
-- Data for Name: tokens; Type: TABLE DATA; Schema: public; Owner: base_project
--

COPY public.tokens (id, created_at, updated_at, deleted_at, value, type, model_id, model_type, expires_at) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: base_project
--

COPY public.users (id, created_at, updated_at, deleted_at, email, password, activated_at) FROM stdin;
\.


--
-- Data for Name: websites; Type: TABLE DATA; Schema: public; Owner: base_project
--

COPY public.websites (id, created_at, updated_at, deleted_at, title, description, url) FROM stdin;
1	2022-11-01 07:35:15.126727+00	2022-11-01 07:35:15.126727+00	\N	A Tour of Go	A Tour of Go has several interactive examples of how Go which you can learn from. There is a menu available if you would like to skip to different sections.	https://go.dev/tour/welcome/1
2	2022-11-01 07:35:15.135313+00	2022-11-01 07:35:15.135313+00	\N	Go by Example	As described on the website: Go by Example is a hands-on introduction to Go using annotated example programs. I have used this site many times as a reference when I need to look something up.	https://gobyexample.com/
3	2022-11-01 07:35:15.140896+00	2022-11-01 07:35:15.140896+00	\N	Go.dev	Learn how to install Go on your machine and read the documentation on the Go website.	https://go.dev/learn/
4	2022-11-01 07:35:15.146712+00	2022-11-01 07:35:15.146712+00	\N	Uberswe on Github	I am the creator of Golang Base Project. This is my Github profile.	https://github.com/uberswe
5	2022-11-01 07:35:15.152236+00	2022-11-01 07:35:15.152236+00	\N	Tournify	A website to create tournaments or free which uses this project as a base.	https://tournify.io
6	2022-11-01 07:35:15.159063+00	2022-11-01 07:35:15.159063+00	\N	GORM	The fantastic ORM library for Golang.	https://gorm.io/
7	2022-11-01 07:35:15.162564+00	2022-11-01 07:35:15.162564+00	\N	Bootstrap	Quickly design and customize responsive mobile-first sites with Bootstrap, the world’s most popular front-end open source toolkit, featuring Sass variables and mixins, responsive grid system, extensive prebuilt components, and powerful JavaScript plugins.	https://getbootstrap.com/
8	2022-11-01 07:35:15.165101+00	2022-11-01 07:35:15.165101+00	\N	Gin Web Framework	Gin is a HTTP web framework written in Go (Golang). It features a Martini-like API with much better performance -- up to 40 times faster. If you need smashing performance, get yourself some Gin.	https://github.com/gin-gonic/gin
\.


--
-- Name: sessions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: base_project
--

SELECT pg_catalog.setval('public.sessions_id_seq', 1, false);


--
-- Name: tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: base_project
--

SELECT pg_catalog.setval('public.tokens_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: base_project
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: websites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: base_project
--

SELECT pg_catalog.setval('public.websites_id_seq', 8, true);


--
-- Name: sessions sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: base_project
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT sessions_pkey PRIMARY KEY (id);


--
-- Name: tokens tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: base_project
--

ALTER TABLE ONLY public.tokens
    ADD CONSTRAINT tokens_pkey PRIMARY KEY (id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: base_project
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: websites websites_pkey; Type: CONSTRAINT; Schema: public; Owner: base_project
--

ALTER TABLE ONLY public.websites
    ADD CONSTRAINT websites_pkey PRIMARY KEY (id);


--
-- Name: idx_sessions_deleted_at; Type: INDEX; Schema: public; Owner: base_project
--

CREATE INDEX idx_sessions_deleted_at ON public.sessions USING btree (deleted_at);


--
-- Name: idx_tokens_deleted_at; Type: INDEX; Schema: public; Owner: base_project
--

CREATE INDEX idx_tokens_deleted_at ON public.tokens USING btree (deleted_at);


--
-- Name: idx_users_deleted_at; Type: INDEX; Schema: public; Owner: base_project
--

CREATE INDEX idx_users_deleted_at ON public.users USING btree (deleted_at);


--
-- Name: idx_websites_deleted_at; Type: INDEX; Schema: public; Owner: base_project
--

CREATE INDEX idx_websites_deleted_at ON public.websites USING btree (deleted_at);


--
-- Name: sessions fk_users_sessions; Type: FK CONSTRAINT; Schema: public; Owner: base_project
--

ALTER TABLE ONLY public.sessions
    ADD CONSTRAINT fk_users_sessions FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

`

`

**Comment by michael-keyes** [comment]
Here is the env.go variables
```
	c.Database = "postgres"
	if os.Getenv("DATABASE") != "" {
		c.Database = os.Getenv("DATABASE")
	}
	if os.Getenv("DATABASE_NAME") != "base_project" {
		c.DatabaseName = os.Getenv("DATABASE_NAME")
	}
	if os.Getenv("DATABASE_HOST") != "localhost" {
		c.DatabaseHost = os.Getenv("DATABASE_HOST")
	}
	if os.Getenv("DATABASE_PORT") != "5432" {
		c.DatabasePort = os.Getenv("DATABASE_PORT")
	}
	if os.Getenv("DATABASE_USERNAME") != "postgres" {
		c.DatabaseUsername = os.Getenv("DATABASE_USERNAME")
	}
	if os.Getenv("DATABASE_PASSWORD") != "mypassword" {
		c.DatabasePassword = os.Getenv("DATABASE_PASSWORD")
	}
```

**Comment by michael-keyes** [comment]
Possibly an issue with Go 1.19?

**Comment by uberswe** [comment]
> Possibly an issue with Go 1.19?

There should be no problem with GO 1.19. Did you try the GORM sample code and did that give you the same error or did it work?
> dial tcp :0: connect: connection refused

**Comment by michael-keyes** [comment]
> > Did you try the GORM sample code and did that give you the same error or did it work?
> 
> > dial tcp :0: connect: connection refused

Yes. Same result.

**Comment by uberswe** [comment]
Then it's most likely an issue with your local environment. Perhaps a port is wrong or maybe you can try 127.0.0.1 instead of localhost. Something locally on your machine is preventing you from connecting.

**Comment by michael-keyes** [comment]
> Then it's most likely an issue with your local environment. Perhaps a port is wrong or maybe you can try 127.0.0.1 instead of localhost. Something locally on your machine is preventing you from connecting.

Thanks for you help with this. I'm not sure my environment is the problem in that my other Go projects run locally using Postgres without issues. 

I've tried creating a database with and without tables and that hasn't worked. Perhaps that tables I create are not correct? Could that be the issue?

**Comment by michael-keyes** [comment]
Decided it would be best to start fresh. 
Using these parameters:
```
	c.Database = "postgres"
	if os.Getenv("DATABASE") != "" {
		c.Database = os.Getenv("DATABASE")
	}
	if os.Getenv("DATABASE_NAME") != "base" {
		c.DatabaseName = os.Getenv("DATABASE_NAME")
	}
	if os.Getenv("DATABASE_HOST") != "localhost" {
		c.DatabaseHost = os.Getenv("DATABASE_HOST")
	}
	if os.Getenv("DATABASE_PORT") != "5432" {
		c.DatabasePort = os.Getenv("DATABASE_PORT")
	}
	if os.Getenv("DATABASE_USERNAME") != "postgres" {
		c.DatabaseUsername = os.Getenv("DATABASE_USERNAME")
	}
	if os.Getenv("DATABASE_PASSWORD") != "mypassword" {
		c.DatabasePassword = os.Getenv("DATABASE_PASSWORD")
	}
```

I now get this:
```
[error] failed to initialize database, got error cannot parse `host= user= password=xxxxx dbname= port= sslmode=disable TimeZone=UTC`: invalid port (strconv.ParseUint: parsing "sslmode=disable": invalid syntax)
```

**Comment by uberswe** [comment]
Sorry, I didn't realize you were changing the env.go file. You should set these variables in your environment, not modify the file. If you want to add them to the file directly, which I do not recommend, then you can do it like so:

```
c.Database = "postgres"
c.DatabaseName = "base"
c.DatabaseHost = "localhost"
c.DatabasePort = "5432"
c.DatabaseUsername = "postgres"
c.DatabasePassword = "mypassword"
```

**Comment by michael-keyes** [comment]
Thank you for getting back to me so quickly.

"You should set these variables in your environment"
Do you mean that I should not alter the env.go file, but instead create a .env file in the main directory?

**Comment by uberswe** [comment]
No, this project does not support a .env file out of the box. This Go By Example link has a pretty good explanation of how environmental variables work https://gobyexample.com/environment-variables

The reason you don't want to hardcode things like your database password is because you generally don't want to store unecrypted secrets in your github repo and if you were to deploy your program it should not use the same credentials on your production server preferably. There are probably better and more detailed explanations for why this is bad practice but that's two simple reasons.

**Comment by uberswe** [comment]
And also how you set environment variables can vary depending on your OS and local environment.

**Comment by michael-keyes** [comment]
Thank you very much. I'll let you know how it goes. Sorry for having to explain so much.

**Comment by michael-keyes** [comment]
Everything works as advertised. Thank you so much for your help. Amazing job on this project!

**Comment by uberswe** [comment]
Glad I could help 😃
