### ISSUE TITLE
SSL problem on demo site

### ISSUE THREAD

**Issue by mishop** [uberswe/golang-base-project#23]
Can you please correct this. I'd like to see what it looks like.
<img width="890" alt="Screenshot 2022-12-11 at 19 36 21" src="https://user-images.githubusercontent.com/816233/206922337-eeecc308-1e52-44b7-80e4-e9a319ab6beb.png">

**Comment by uberswe** [comment]
Thanks for letting me know. The domain had expired and I missed it. It's renewed now and it may take some time for DNS to resolve the domain but please let me know if it's not working again within the next 48 hours by reopening this issue. For me it works and therefore I will close this.
