### ISSUE TITLE
Unable to send mail unless testing on localhost

### ISSUE THREAD

**Issue by michael-keyes** [uberswe/golang-base-project#25]
Hello.
I'm unable to send emails unless on localhost. Any ideas as to why this might happen? Running pocketbase on the same server with the same configs and it's able to send emails. Thanks for any help you can provide

**Comment by uberswe** [comment]
Do you have any logs and what provider are you using to send email with? Are you seeing any errors?

The problem could be something simple like env variables or something with the server, it's hard to guess without more information

**Comment by michael-keyes** [comment]
I'm not sure how to get logs while running the binary as a service. I'm using hosting my own email server. That server works with pocketbase and localhost only golang-base-project. The env variables likely correct in that it works on localhost.

**Comment by michael-keyes** [comment]
Issue with env variables. Solved using godotenv
