### ISSUE TITLE
env variables

### ISSUE THREAD

**Issue by Jimmy99** [uberswe/golang-base-project#6]
Hi 

Where exactly do you change the env variables for sending email? Is it in the docker-compose.yml file?

**Comment by uberswe** [comment]
Yes exactly, currently the project supports SMTP credentials so if you use docker you can change them here or override this default docker-compose file with your own: https://github.com/uberswe/golang-base-project/blob/main/docker-compose.yml#L27-L31

You can also provide env variables when you run the command like so: `SMTP_USERNAME=markus@golangbase.com SMTP_PASSWORD=somecleverpassword go run cmd/base/main.go`

Or you could set them on the machine the application is running on. Twilio seems to have a decent guide but I have not read it fully: https://www.twilio.com/blog/2017/01/how-to-set-environment-variables.html

I hope that answered your question and will close the issue but if you have further issues or questions feel free to reopen this.
